# Generated by Django 6.0 on 2026-01-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo/"),
        ),
    ]
