# Generated by Django 6.0 on 2025-12-19 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("roll_number", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=15)),
                ("image", models.ImageField(upload_to="media/img")),
                ("course", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("address", models.TextField()),
                ("guardian_name", models.CharField(max_length=100)),
                ("guardian_phone", models.CharField(max_length=15)),
                ("status", models.IntegerField(default=0)),
                ("approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
